on: 
  pull_request:
    branches:
      - develop
name: Sonarscanner and PR decoration
jobs:
  sonarscanner-pr-decoration:
    runs-on: ubuntu-latest
    name: Sonarscanner and PR decoration
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: '0'
      - run: git fetch origin develop
        name: Fetching develop branch
      #- uses: highbyte/sonarscan-dotnet@2.0
      - uses: pherms/sonarscan-dotnet@main
        name: SonarScanner for .NET 5 with pull request decoration support
        with:
          # The key of the SonarQube project
          sonarProjectKey: testproject.pascal
          # The name of the SonarQube project
          sonarProjectName:  "testproject.pascal"
          dotnetBuildArguments: Ryujinx.sln
          # The SonarQube server URL. For SonarCloud, skip this setting.
          sonarHostname:  https://codequality.xablu.com
          # Pass github event pull_request head sha
          sonarBeginArguments: /d:sonar.scm.revision=${{ github.event.pull_request.head.sha }}
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBEPROD_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
