on:
  workflow_dispatch:
    branches:
      - develop
      - release-alpha
      - release-beta
      - release-store
  push:
    branches:
      - develop
      - release-alpha
      - release-beta
      - release-store
name: Built Testproject App in Appcenter
jobs:
  AppcenterBuildTrigger:
    name: ${{ matrix.appname }} Build Trigger Appcenter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        appname: [testproject, testproject-1]
    steps:
    - uses: actions/checkout@v2
      name: Checkout branch
    - name: ${{ matrix.appname}} develop branch Appcenter trigger
      if: contains(github.ref, 'develop')
      uses: xablu/github-appcenterbuild-action@main
      with:
        appcentertoken: ${{ secrets.APPCENTER_COMMIT_ACTION_ALL_APPS }}
        organization: p.herms-xablu.com
        application: ${{ matrix.appname }}
        branch: develop
    - name: ${{ matrix.appname}} release-alpha branch Appcenter trigger
      if: contains(github.ref, 'release-alpha')
      uses: xablu/github-appcenterbuild-action@main
      with:
        appcentertoken: ${{ secrets.APPCENTER_COMMIT_ACTION_ALL_APPS }}
        organization: p.herms-xablu.com
        application: ${{ matrix.appname }}
        branch: release-alpha
    - name: ${{ matrix.appname}} release-beta branch Appcenter trigger
      if: contains(github.ref, 'release-beta')
      uses: xablu/github-appcenterbuild-action@main
      with:
        appcentertoken: ${{ secrets.APPCENTER_COMMIT_ACTION_ALL_APPS }}
        organization: p.herms-xablu.com
        application: ${{ matrix.appname }}
        branch: release-beta
    - name: ${{ matrix.appname}} release-alpha branch Appcenter trigger
      if: contains(github.ref, 'release-store')
      uses: xablu/github-appcenterbuild-action@main
      with:
        appcentertoken: ${{ secrets.APPCENTER_COMMIT_ACTION_ALL_APPS }}
        organization: p.herms-xablu.com
        application: ${{ matrix.appname }}
        branch: release-store
 
